### ISSUE TITLE
Failures

### ISSUE THREAD

**Issue by TonyRenHK** [financialforcedev/ffhttp-googlesheets#1]
Failures
![2016-09-27 11_13_34-deployment details _ salesforce](https://cloud.githubusercontent.com/assets/9688136/18859113/cdfcb1be-84a3-11e6-9b1d-255072e5ed18.png)
:
classes/ffhttp_GoogleSheets.cls(42,29):Invalid type: ffhttp_Client.Credentials
classes/ffhttp_GoogleSheetsModelAbstractObject.cls(33,86):Invalid type: ffhttp_IHttpContent
classes/ffhttp_GoogleSheetsModelBatch.cls(32,65):Dependent class is invalid and needs recompilation:
ffhttp_GoogleSheetsModelAbstractObject: line 33, column 86: Invalid type: ffhttp_IHttpContent
classes/ffhttp_GoogleSheetsModelCell.cls(45,64):Dependent class is invalid and needs recompilation:
ffhttp_GoogleSheetsModelAbstractObject: line 33, column 86: Invalid type: ffhttp_IHttpContent
classes/ffhttp_GoogleSheetsModelSheet.cls(49,65):Dependent class is invalid and needs recompilation:
ffhttp_GoogleSheetsModelAbstractObject: line 33, column 86: Invalid type: ffhttp_IHttpContent
classes/ffhttp_GoogleSheetsModelTest.cls(75,3):Dependent class is invalid and needs recompilation:
ffhttp_GoogleSheetsModelSheet: line 49, column 65: Dependent class is invalid and needs recompilation:
ffhttp_GoogleSheetsModelAbstractObject: line 33, column 86: Invalid type: ffhttp_IHttpContent
classes/ffhttp_GoogleSheetsModelWorksheet.cls(50,69):Dependent class is invalid and needs recompilation:
ffhttp_GoogleSheetsModelAbstractObject: line 33, column 86: Invalid type: ffhttp_IHttpContent
classes/ffhttp_GoogleSheetsSpreadsheets.cls(32,67):Dependent class is invalid and needs recompilation:
ffhttp_GoogleSheetsResource: line 51, column 10: Dependent class is invalid and needs recompilation:
ffhttp_GoogleSheets: line 42, column 29: Invalid type: ffhttp_Client.Credentials
classes/ffhttp_GoogleSheetsTest.cls(43,45):Dependent class is invalid and needs recompilation:
ffhttp_GoogleSheetsModelBatch: line 32, column 65: Dependent class is invalid and needs recompilation:
ffhttp_GoogleSheetsModelAbstractObject: line 33, column 86: Invalid type: ffhttp_IHttpContent
classes/ffhttp_GoogleSheetsResource.cls(51,10):Dependent class is invalid and needs recompilation:
ffhttp_GoogleSheets: line 42, column 29: Invalid type: ffhttp_Client.Credentials
classes/ffhttp_GoogleSheetsWorksheets.cls(32,65):Dependent class is invalid and needs recompilation:
ffhttp_GoogleSheetsResource: line 51, column 10: Dependent class is invalid and needs recompilation:
ffhttp_GoogleSheets: line 42, column 29: Invalid type: ffhttp_Client.Credentials
classes/ffhttp_GoogleSheetsCells.cls(40,34):Dependent class is invalid and needs recompilation:
ffhttp_GoogleSheets: line 42, column 29: Invalid type: ffhttp_Client.Credentials

**Comment by mwoodcertinia** [comment]
Hi Tony,

Can you check that you have deployed the Core library (https://github.com/financialforcedev/ffhttp-core), as explained in the configuration section of the Readme file (https://github.com/financialforcedev/ffhttp-googlesheets#configuration)? Each of the ffhttp libraries is dependent on this being deployed first.

If you are still having problems then I'm happy to take a further look at this.

Cheers,

Matt
